apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: caas1
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium
      storageClass: wcp-storage-general
    workers:
      count: 2
      class: best-effort-large
      storageClass: wcp-storage-general
  distribution:
    fullVersion: v1.17.7+vmware.1-tkg.1.154236c
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
