kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: wcp-storage-general
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
